'use strict';

/**
 * 初始题库 60 道 · 初中形容词比较级 / 最高级
 * 字段：t 题型(choice|fill|fix)  d 难度(1易 2中 3难)  tag 语法点
 *      stem 题干  zh 中文提示  opts 选项  ans 答案(多个可接受答案用 | 分隔)
 *      ez 中文规则解释  ee 英文正确例句(同时作为朗读文本)
 */
const Q = [
  // ── reg_er 单音节形容词 +er / +est (8) ──────────────────────────────
  { t:"choice", d:1, tag:"reg_er", stem:"My brother is ___ than me.  (tall)", zh:"我哥哥比我高。",
    opts:["taller","tallest","more tall","tall"], ans:"taller",
    ez:"tall 是单音节形容词，比较级直接加 -er，最高级加 -est。句中出现 than，必须用比较级。",
    ee:"My brother is taller than me." },
  { t:"choice", d:1, tag:"reg_er", stem:"Who is the ___ runner in your class?  (fast)", zh:"谁是你们班跑得最快的？",
    opts:["fastest","faster","most fast","fast"], ans:"fastest",
    ez:"单音节形容词最高级加 -est，前面加 the。单音节词不用 most。",
    ee:"Who is the fastest runner in your class?" },
  { t:"fill", d:1, tag:"reg_er", stem:"This river is ___ than that one.  (long)", zh:"这条河比那条长。填 long 的正确形式。",
    opts:[], ans:"longer",
    ez:"long → longer → longest。单音节词直接加 -er / -est。",
    ee:"This river is longer than that one." },
  { t:"choice", d:1, tag:"reg_er", stem:"Winter is the ___ season of the year.  (cold)", zh:"冬天是一年中最冷的季节。",
    opts:["coldest","colder","most cold","cold"], ans:"coldest",
    ez:"of the year 表示范围，说明是三者以上比较，用最高级 the coldest。",
    ee:"Winter is the coldest season of the year." },
  { t:"choice", d:2, tag:"reg_er", stem:"Your bag is ___ than mine, but his is the ___.  (small)", zh:"你的包比我的小，但他的最小。",
    opts:["smaller; smallest","smallest; smaller","small; smaller","smaller; more small"], ans:"smaller; smallest",
    ez:"than 前用比较级 smaller；the 后表示三者以上最小，用最高级 smallest。",
    ee:"Your bag is smaller than mine, but his is the smallest." },
  { t:"fill", d:1, tag:"reg_er", stem:"He jumped ___ than any other boy.  (high)", zh:"他跳得比任何其他男孩都高。",
    opts:[], ans:"higher",
    ez:"比较级 + than any other + 单数名词，表示“比其他所有都……”，相当于最高级。",
    ee:"He jumped higher than any other boy." },
  { t:"choice", d:2, tag:"reg_er", stem:"Tom works ___ than Jack.  (hard)", zh:"汤姆比杰克更努力。注意 hardly 的陷阱。",
    opts:["harder","hardest","more hard","hardly"], ans:"harder",
    ez:"hard 的比较级是 harder。注意 hardly 不是 hard 的比较级，它是“几乎不”，意思完全相反！",
    ee:"Tom works harder than Jack." },
  { t:"fix", d:2, tag:"reg_er", stem:"My sister is more young than me.", zh:"改错：找出错误并写出正确形式。",
    opts:[], ans:"younger",
    ez:"young 是单音节形容词，比较级直接加 -er 变 younger，不能用 more。more 只用于多音节形容词。",
    ee:"My sister is younger than me." },

  // ── reg_e 以 e 结尾 +r / +st (5) ───────────────────────────────────
  { t:"choice", d:1, tag:"reg_e", stem:"This flower is ___ than that one.  (nice)", zh:"这朵花比那朵好看。",
    opts:["nicer","niceer","more nice","nicest"], ans:"nicer",
    ez:"以字母 e 结尾的形容词，比较级只加 -r，最高级只加 -st。nice → nicer → nicest，不能写成 niceer。",
    ee:"This flower is nicer than that one." },
  { t:"fill", d:1, tag:"reg_e", stem:"Your room is ___ than mine.  (large)", zh:"你的房间比我的大。",
    opts:[], ans:"larger",
    ez:"large 以 e 结尾，比较级只加 -r：large → larger → largest。",
    ee:"Your room is larger than mine." },
  { t:"choice", d:2, tag:"reg_e", stem:"It is the ___ way to go home.  (safe)", zh:"这是回家最安全的路。",
    opts:["safest","safeest","most safe","safer"], ans:"safest",
    ez:"safe 以 e 结尾，最高级只加 -st：safe → safer → safest。",
    ee:"It is the safest way to go home." },
  { t:"choice", d:2, tag:"reg_e", stem:"Please come ___ tomorrow.  (late)", zh:"明天请晚点来。注意 latter 的陷阱。",
    opts:["later","latest","more late","latter"], ans:"later",
    ez:"late → later → latest。latter 意思是“后者”，不是比较级，别混淆。",
    ee:"Please come later tomorrow." },
  { t:"fix", d:2, tag:"reg_e", stem:"The blue one is the largeest of the three.", zh:"改错：找出拼写错误并改正。",
    opts:[], ans:"largest",
    ez:"large 已经以 e 结尾，最高级只加 -st，写作 largest，不是 largeest。",
    ee:"The blue one is the largest of the three." },

  // ── reg_y 辅音字母+y → ier / iest (7) ──────────────────────────────
  { t:"choice", d:1, tag:"reg_y", stem:"She looks ___ than yesterday.  (happy)", zh:"她看起来比昨天开心。",
    opts:["happier","happyer","more happy","happiest"], ans:"happier",
    ez:"以“辅音字母 + y”结尾，要先把 y 变成 i，再加 -er / -est：happy → happier → happiest。",
    ee:"She looks happier than yesterday." },
  { t:"choice", d:1, tag:"reg_y", stem:"Maths is ___ than English for me.  (easy)", zh:"对我来说数学比英语简单。",
    opts:["easier","easyer","more easy","easiest"], ans:"easier",
    ez:"easy 结尾是“辅音 s + y”，变 i 加 -er：easy → easier → easiest。",
    ee:"Maths is easier than English for me." },
  { t:"fill", d:2, tag:"reg_y", stem:"My mother is the ___ person in my family.  (busy)", zh:"我妈妈是家里最忙的人。",
    opts:[], ans:"busiest",
    ez:"busy → busier → busiest。变 y 为 i 再加 -est。",
    ee:"My mother is the busiest person in my family." },
  { t:"choice", d:2, tag:"reg_y", stem:"I get up ___ than my sister.  (early)", zh:"我比我妹妹起得早。",
    opts:["earlier","more early","earliest","early"], ans:"earlier",
    ez:"early 虽然是双音节，但以“辅音 + y”结尾，仍然变 y 为 i 加 -er：earlier，不用 more。",
    ee:"I get up earlier than my sister." },
  { t:"choice", d:2, tag:"reg_y", stem:"This bag is ___ than that one.  (heavy)", zh:"这个包比那个重。",
    opts:["heavier","more heavy","heavyer","heaviest"], ans:"heavier",
    ez:"heavy → heavier → heaviest。以“辅音 + y”结尾的双音节词也走变 i 加 -er 的规则。",
    ee:"This bag is heavier than that one." },
  { t:"fill", d:2, tag:"reg_y", stem:"It was the ___ story I have ever heard.  (funny)", zh:"这是我听过最好笑的故事。",
    opts:[], ans:"funniest",
    ez:"funny → funnier → funniest。the + 最高级 + I have ever ... 是常考句型。",
    ee:"It was the funniest story I have ever heard." },
  { t:"fix", d:3, tag:"reg_y", stem:"Lucy is the prettyest girl in our class.", zh:"改错：找出拼写错误并改正。",
    opts:[], ans:"prettiest",
    ez:"pretty 以“辅音 t + y”结尾，最高级要变 y 为 i 再加 -est：prettiest。",
    ee:"Lucy is the prettiest girl in our class." },

  // ── reg_double 重读闭音节双写末尾辅音 (6) ───────────────────────────
  { t:"choice", d:1, tag:"reg_double", stem:"An elephant is ___ than a horse.  (big)", zh:"大象比马大。",
    opts:["bigger","biger","more big","biggest"], ans:"bigger",
    ez:"重读闭音节（辅音+元音+辅音）结尾，要双写末尾辅音字母再加 -er：big → bigger → biggest。",
    ee:"An elephant is bigger than a horse." },
  { t:"choice", d:1, tag:"reg_double", stem:"July is the ___ month here.  (hot)", zh:"七月是这里最热的月份。",
    opts:["hottest","hotest","most hot","hotter"], ans:"hottest",
    ez:"hot 是重读闭音节，双写 t 再加 -est：hot → hotter → hottest。",
    ee:"July is the hottest month here." },
  { t:"fill", d:2, tag:"reg_double", stem:"This line is ___ than that one.  (thin)", zh:"这条线比那条细。",
    opts:[], ans:"thinner",
    ez:"thin → thinner → thinnest。双写末尾的 n 再加 -er。",
    ee:"This line is thinner than that one." },
  { t:"choice", d:2, tag:"reg_double", stem:"Don't let your clothes get ___ in the rain.  (wet)", zh:"别让衣服在雨里更湿了。",
    opts:["wetter","weter","more wet","wettest"], ans:"wetter",
    ez:"wet 是重读闭音节，双写 t 加 -er：wet → wetter → wettest。",
    ee:"Don't let your clothes get wetter in the rain." },
  { t:"choice", d:2, tag:"reg_double", stem:"The film made me ___ than the book did.  (sad)", zh:"这部电影比那本书更让我难过。",
    opts:["sadder","sader","more sad","saddest"], ans:"sadder",
    ez:"sad 是重读闭音节，双写 d 加 -er：sad → sadder → saddest。",
    ee:"The film made me sadder than the book did." },
  { t:"fix", d:3, tag:"reg_double", stem:"Today is hoter than yesterday.", zh:"改错：找出拼写错误并改正。",
    opts:[], ans:"hotter",
    ez:"hot 只有一个辅音字母结尾且是重读闭音节，必须双写成 hotter，不能只写 hoter。",
    ee:"Today is hotter than yesterday." },

  // ── more_most 多音节形容词 (8) ─────────────────────────────────────
  { t:"choice", d:1, tag:"more_most", stem:"This story is ___ than that one.  (interesting)", zh:"这个故事比那个有趣。",
    opts:["more interesting","interestinger","most interesting","interesting"], ans:"more interesting",
    ez:"三个及以上音节的形容词，比较级在前面加 more，最高级加 the most，不能加 -er / -est。",
    ee:"This story is more interesting than that one." },
  { t:"choice", d:1, tag:"more_most", stem:"She is the ___ girl in our school.  (beautiful)", zh:"她是我们学校最漂亮的女孩。",
    opts:["most beautiful","beautifulest","more beautiful","beautiful"], ans:"most beautiful",
    ez:"beautiful 是多音节形容词，最高级用 the most beautiful。",
    ee:"She is the most beautiful girl in our school." },
  { t:"fill", d:2, tag:"more_most", stem:"Health is ___ than money.  (important)", zh:"健康比金钱更重要。填两个词。",
    opts:[], ans:"more important",
    ez:"important 是多音节形容词，比较级是 more important。",
    ee:"Health is more important than money." },
  { t:"choice", d:2, tag:"more_most", stem:"This question is the ___ of the three.  (difficult)", zh:"这道题是三道里最难的。",
    opts:["most difficult","more difficult","difficultest","difficult"], ans:"most difficult",
    ez:"of the three 表示三者比较，用最高级；difficult 是多音节词，用 the most difficult。",
    ee:"This question is the most difficult of the three." },
  { t:"choice", d:2, tag:"more_most", stem:"These shoes are ___ than those ones.  (expensive)", zh:"这双鞋比那双贵。",
    opts:["more expensive","expensiver","most expensive","expensive"], ans:"more expensive",
    ez:"expensive 是多音节形容词，比较级 more expensive，最高级 the most expensive。",
    ee:"These shoes are more expensive than those ones." },
  { t:"fill", d:2, tag:"more_most", stem:"Football is the ___ sport in the world.  (popular)", zh:"足球是世界上最流行的运动。填两个词。",
    opts:[], ans:"most popular",
    ez:"popular 是多音节形容词，最高级是 the most popular。",
    ee:"Football is the most popular sport in the world." },
  { t:"choice", d:3, tag:"more_most", stem:"You should be ___ with your handwriting.  (careful)", zh:"你写字应该更认真些。",
    opts:["more careful","carefuler","most careful","careful"], ans:"more careful",
    ez:"careful 虽然只有两个音节，但以 -ful 结尾，同样用 more / most 构成比较级和最高级。",
    ee:"You should be more careful with your handwriting." },
  { t:"fix", d:3, tag:"more_most", stem:"This film is excitinger than that one.", zh:"改错：找出错误并写出正确形式（两个词）。",
    opts:[], ans:"more exciting",
    ez:"exciting 是多音节形容词，比较级必须用 more exciting，不能加 -er。",
    ee:"This film is more exciting than that one." },

  // ── irregular 不规则变化 (8) ───────────────────────────────────────
  { t:"choice", d:1, tag:"irregular", stem:"Her English is ___ than mine.  (good)", zh:"她的英语比我的好。",
    opts:["better","gooder","best","more good"], ans:"better",
    ez:"good / well 的不规则变化：good → better → best。必须背下来，没有 gooder 这个词。",
    ee:"Her English is better than mine." },
  { t:"choice", d:1, tag:"irregular", stem:"This is the ___ film I have ever seen.  (bad)", zh:"这是我看过最糟的电影。",
    opts:["worst","baddest","worse","most bad"], ans:"worst",
    ez:"bad / badly / ill 的不规则变化：bad → worse → worst。没有 baddest。",
    ee:"This is the worst film I have ever seen." },
  { t:"fill", d:2, tag:"irregular", stem:"I have ___ books than you.  (many)", zh:"我的书比你多。",
    opts:[], ans:"more",
    ez:"many / much 的不规则变化：many → more → most。注意 more 既是 many 的比较级，也用于构成多音节词的比较级。",
    ee:"I have more books than you." },
  { t:"choice", d:2, tag:"irregular", stem:"He spends ___ time on games than before.  (little)", zh:"他花在游戏上的时间比以前少。",
    opts:["less","littler","least","littlest"], ans:"less",
    ez:"little 的不规则变化：little → less → least。修饰不可数名词 time 用 less。",
    ee:"He spends less time on games than before." },
  { t:"choice", d:2, tag:"irregular", stem:"My home is ___ from school than yours.  (far)", zh:"我家离学校比你家远。",
    opts:["farther","farer","farthest","far"], ans:"farther",
    ez:"far 有两组变化：far → farther → farthest（指距离），far → further → furthest（指程度，也可指距离）。没有 farer。",
    ee:"My home is farther from school than yours." },
  { t:"fill", d:2, tag:"irregular", stem:"Which do you like ___, tea or coffee?  (well)", zh:"茶和咖啡你更喜欢哪个？",
    opts:[], ans:"better",
    ez:"well → better → best。两者之间选择用比较级 better，like ... better 是“更喜欢”。",
    ee:"Which do you like better, tea or coffee?" },
  { t:"choice", d:3, tag:"irregular", stem:"Of all the subjects, I like maths ___.  (well)", zh:"所有科目里我最喜欢数学。",
    opts:["best","better","the better","most"], ans:"best",
    ez:"of all 表示三者以上，用最高级 best。副词最高级前面的 the 可以省略。",
    ee:"Of all the subjects, I like maths best." },
  { t:"fix", d:3, tag:"irregular", stem:"She sings more better than her sister.", zh:"改错：找出多余的词，写出正确形式。",
    opts:[], ans:"better",
    ez:"better 本身已经是比较级，前面不能再加 more。more + 比较级是典型的中式英语错误。",
    ee:"She sings better than her sister." },

  // ── than 比较句式 (4) ──────────────────────────────────────────────
  { t:"choice", d:1, tag:"than", stem:"Tom runs faster ___ Jack.", zh:"汤姆跑得比杰克快。",
    opts:["than","then","as","that"], ans:"than",
    ez:"比较级后面接比较对象用 than（比）。注意别和 then（然后）混淆，这两个词拼写只差一个字母。",
    ee:"Tom runs faster than Jack." },
  { t:"fill", d:2, tag:"than", stem:"She is taller ___ I am.", zh:"她比我高。填一个词。",
    opts:[], ans:"than",
    ez:"比较级 + than + 比较对象。than 后面可以接完整的句子 I am，也可以只接 me。",
    ee:"She is taller than I am." },
  { t:"choice", d:2, tag:"than", stem:"My book is newer than ___.  (you)", zh:"我的书比你的新。",
    opts:["yours","your","you're","you"], ans:"yours",
    ez:"比较对象必须同类：书对书。所以要用名词性物主代词 yours（= your book），不能用 you（人）。",
    ee:"My book is newer than yours." },
  { t:"fix", d:3, tag:"than", stem:"The population of China is larger than India.", zh:"改错：比较对象不一致，写出 than 后面正确的部分。",
    opts:[], ans:"that of India|than that of India",
    ez:"比较对象要同类：人口对人口。China 的人口要和 India 的人口比，所以用 that of India（that 指代 the population）。",
    ee:"The population of China is larger than that of India." },

  // ── as_as 同级比较 (5) ─────────────────────────────────────────────
  { t:"choice", d:1, tag:"as_as", stem:"She is as ___ as her sister.  (tall)", zh:"她和她姐姐一样高。",
    opts:["tall","taller","tallest","more tall"], ans:"tall",
    ez:"as ... as 之间必须用形容词原级，表示“和……一样”。这是最常考的陷阱，看到 as...as 立刻想到原级。",
    ee:"She is as tall as her sister." },
  { t:"choice", d:2, tag:"as_as", stem:"This book is not as ___ as that one.  (interesting)", zh:"这本书不如那本有趣。",
    opts:["interesting","more interesting","most interesting","interestinger"], ans:"interesting",
    ez:"not as ... as 表示“不如……”，中间同样用原级，多音节词也不加 more。",
    ee:"This book is not as interesting as that one." },
  { t:"fill", d:2, tag:"as_as", stem:"Your bag is as ___ as mine.  (heavy)", zh:"你的包和我的一样重。",
    opts:[], ans:"heavy",
    ez:"as ... as 中间用原级 heavy，不是 heavier。",
    ee:"Your bag is as heavy as mine." },
  { t:"choice", d:2, tag:"as_as", stem:"He doesn't run ___ fast as you.", zh:"他跑得不如你快。",
    opts:["so","very","too","much"], ans:"so",
    ez:"否定的同级比较可以用 not so ... as 或 not as ... as，两种都对。very / too / much 都不能用在这个句型里。",
    ee:"He doesn't run so fast as you." },
  { t:"fix", d:3, tag:"as_as", stem:"This room is as larger as that one.", zh:"改错：找出错误并写出正确形式。",
    opts:[], ans:"large",
    ez:"as ... as 之间只能用原级 large，不能用比较级 larger。",
    ee:"This room is as large as that one." },

  // ── the_sup_range 最高级的范围 (3) ─────────────────────────────────
  { t:"choice", d:1, tag:"the_sup_range", stem:"He is the tallest ___ our class.", zh:"他是我们班最高的。",
    opts:["in","of","at","on"], ans:"in",
    ez:"最高级的范围如果是一个“团体/地点”（class、school、world、family），用 in。",
    ee:"He is the tallest in our class." },
  { t:"choice", d:2, tag:"the_sup_range", stem:"Lily is the youngest ___ the three girls.", zh:"莉莉是三个女孩里最小的。",
    opts:["of","in","among","from"], ans:"of",
    ez:"最高级的范围如果是“同类事物的集合”（the three girls、all the students、us all），用 of。口诀：团体用 in，同类用 of。",
    ee:"Lily is the youngest of the three girls." },
  { t:"fix", d:2, tag:"the_sup_range", stem:"She is tallest girl in our class.", zh:"改错：漏了一个词，写出正确形式（两个词）。",
    opts:[], ans:"the tallest",
    ez:"形容词最高级前面必须加定冠词 the：the tallest girl。（副词最高级前的 the 才可以省略。）",
    ee:"She is the tallest girl in our class." },

  // ── one_of_sup one of the + 最高级 (2) ────────────────────────────
  { t:"choice", d:2, tag:"one_of_sup", stem:"Beijing is one of the biggest ___ in China.", zh:"北京是中国最大的城市之一。",
    opts:["cities","city","the city","citys"], ans:"cities",
    ez:"one of the + 最高级 + 复数名词，表示“最……之一”。city 的复数是 cities（变 y 为 i 加 es）。",
    ee:"Beijing is one of the biggest cities in China." },
  { t:"fix", d:3, tag:"one_of_sup", stem:"He is one of the best student in our school.", zh:"改错：找出错误并写出正确形式。",
    opts:[], ans:"students",
    ez:"one of the + 最高级后面必须跟复数名词，因为“之一”意味着有很多个。改成 students。",
    ee:"He is one of the best students in our school." },

  // ── degree_adv 程度修饰 & 越来越 (2) ───────────────────────────────
  { t:"choice", d:2, tag:"degree_adv", stem:"This room is ___ bigger than that one.", zh:"这个房间比那个大得多。",
    opts:["much","very","so","too"], ans:"much",
    ez:"修饰比较级要用 much / a lot / far / even / a little，不能用 very。very 只能修饰原级（very big）。",
    ee:"This room is much bigger than that one." },
  { t:"choice", d:3, tag:"degree_adv", stem:"It is getting ___ in spring.  (warm)", zh:"春天天气变得越来越暖和。",
    opts:["warmer and warmer","more and more warm","warm and warm","the warmer"], ans:"warmer and warmer",
    ez:"“比较级 + and + 比较级”表示“越来越……”。多音节词则用 more and more + 原级（more and more beautiful）。",
    ee:"It is getting warmer and warmer in spring." },

  // ── comp_vs_sup 两者比较级 / 三者以上最高级 (2) ────────────────────
  { t:"choice", d:2, tag:"comp_vs_sup", stem:"There are two apples on the table. The red one is ___.  (big)", zh:"桌上有两个苹果，红色的那个更大。",
    opts:["bigger","biggest","the biggest","big"], ans:"bigger",
    ez:"只有两个对象比较，必须用比较级 bigger，即使句子里没有 than。三者及以上才用最高级。",
    ee:"There are two apples on the table. The red one is bigger." },
  { t:"choice", d:3, tag:"comp_vs_sup", stem:"Of the three boys, Tom is ___.  (strong)", zh:"三个男孩里，汤姆最强壮。",
    opts:["the strongest","stronger","the stronger","strongest"], ans:"the strongest",
    ez:"Of the three 表示三者比较，用最高级，且形容词最高级前要加 the：the strongest。",
    ee:"Of the three boys, Tom is the strongest." },
];

function seedQuestions(db) {
  const already = db.prepare('SELECT COUNT(*) AS n FROM questions').get().n;
  if (already > 0) return { inserted: 0, skipped: already };

  const ins = db.prepare(`
    INSERT INTO questions (type, stem, stem_zh, options, answer, rule_tag, difficulty, explain_zh, explain_en, tts_text)
    VALUES (@type, @stem, @stem_zh, @options, @answer, @rule_tag, @difficulty, @explain_zh, @explain_en, @tts_text)
  `);
  const tx = db.transaction(() => {
    for (const q of Q) {
      ins.run({
        type: q.t,
        stem: q.stem,
        stem_zh: q.zh || '',
        options: JSON.stringify(q.opts || []),
        answer: q.ans,
        rule_tag: q.tag,
        difficulty: q.d,
        explain_zh: q.ez || '',
        explain_en: q.ee || '',
        tts_text: q.tts || q.ee || '',
      });
    }
  });
  tx();
  return { inserted: Q.length, skipped: 0 };
}

module.exports = { seedQuestions, QUESTIONS: Q };
